"""Validated photo metadata supplied by the owner, never generated by the writer."""
from datetime import date
import json
from pathlib import Path
import re

VARIABLE_NAME = 'fan_zone_photo_credits'
DEFAULT_CATALOG = Path(__file__).resolve().parents[1] / 'config/photo-credits.json'
MAX_CATALOG_BYTES = 22000


def _text(value, label, maximum):
    if not isinstance(value, str) or not value.strip() or len(value) > maximum or any(
            ord(char) < 32 or ord(char) == 127 for char in value) or re.search(r'[<>]', value):
        raise ValueError('Invalid photo ' + label)
    return value.strip()


def validate_catalog(value):
    """Reject typos/unknown fields rather than silently dropping credit information."""
    if not isinstance(value, dict) or set(value) != {'schema_version', 'assets', 'sha256'} or type(value.get('schema_version')) is not int or value['schema_version'] != 1:
        raise ValueError('Photo credits need schema_version 1, assets and sha256')
    if not isinstance(value['assets'], dict) or not isinstance(value['sha256'], dict):
        raise ValueError('Photo credits assets and sha256 must be objects')
    assets = {}
    for asset_id, entry in value['assets'].items():
        if not isinstance(asset_id, str) or not re.fullmatch(r'[1-9][0-9]{5,19}', asset_id):
            raise ValueError('Invalid Getty asset ID')
        if not isinstance(entry, dict) or not {'caption', 'credit'} <= set(entry) or set(entry) - {'caption', 'credit', 'eventDate', 'alt'}:
            raise ValueError('A photo asset needs caption and credit, with optional eventDate and alt')
        asset = {'caption': _text(entry['caption'], 'caption', 2000), 'credit': _text(entry['credit'], 'credit', 300)}
        if 'eventDate' in entry:
            day = entry['eventDate']
            if not isinstance(day, str) or date.fromisoformat(day).isoformat() != day:
                raise ValueError('Invalid photo eventDate')
            asset['eventDate'] = day
        if 'alt' in entry:
            asset['alt'] = _text(entry['alt'], 'alt', 1000)
        format_caption(asset, '9999-12-31')  # Match the websites' full caption limit before accepting config.
        assets[asset_id] = asset
    hashes = {}
    for checksum, asset_id in value['sha256'].items():
        if not isinstance(checksum, str) or not re.fullmatch(r'[a-f0-9]{64}', checksum) or not isinstance(asset_id, str) or asset_id not in assets:
            raise ValueError('A photo sha256 entry must identify an approved asset')
        hashes[checksum] = asset_id
    result = {'schema_version': 1, 'assets': dict(sorted(assets.items())), 'sha256': dict(sorted(hashes.items()))}
    if len(json.dumps(result, separators=(',', ':'), ensure_ascii=False).encode()) > MAX_CATALOG_BYTES:
        raise ValueError('Photo credits exceed the news transport size limit')
    return result


def load_catalog(path=None):
    return validate_catalog(json.loads(Path(path or DEFAULT_CATALOG).read_text()))


def read_task_catalog():
    """Read at task execution so a Variable edit does not depend on DAG reparsing."""
    from airflow.sdk import Variable
    value = Variable.get(VARIABLE_NAME, default=None, deserialize_json=True)
    return load_catalog() if value is None else validate_catalog(value)


def resolve_credit(catalog, filename=None, sha256=None, metadata=None):
    """Resolve an explicit asset identity; never guess from people or subject text."""
    catalog = validate_catalog(catalog)
    metadata = metadata or {}
    if not isinstance(metadata, dict):
        raise ValueError('Invalid photo metadata')
    matches = set()
    if filename is not None:
        basename = Path(filename).name
        matches.update(asset_id for asset_id in catalog['assets'] if re.search(
            r'(?<![0-9])' + re.escape(asset_id) + r'(?![0-9])', basename))
    if sha256 in catalog['sha256']:
        matches.add(catalog['sha256'][sha256])
    if metadata.get('gettyAssetId') is not None:
        asset_id = metadata['gettyAssetId']
        if not isinstance(asset_id, str) or asset_id not in catalog['assets']:
            raise ValueError('Photo metadata Getty asset is absent from approved credits')
        matches.add(asset_id)
    if len(matches) > 1:
        raise ValueError('Conflicting Getty identities for one photo')
    if matches:
        asset_id = matches.pop()
        return {**catalog['assets'][asset_id], 'gettyAssetId': asset_id}
    # Existing owner-maintained captions/credits remain usable for other providers.
    if metadata.get('caption') and metadata.get('credit'):
        result = {'caption': _text(metadata['caption'], 'caption', 2000),
                  'credit': _text(metadata['credit'], 'credit', 300)}
        if metadata.get('alt'):
            result['alt'] = _text(metadata['alt'], 'alt', 1000)
        if metadata.get('eventDate'):
            day = metadata['eventDate']
            if not isinstance(day, str) or date.fromisoformat(day).isoformat() != day:
                raise ValueError('Invalid photo eventDate')
            result['eventDate'] = day
        format_caption(result, '9999-12-31')
        return result
    return None


def format_caption(credit, publication_day=None):
    caption = credit['caption'].strip()
    event_day = credit.get('eventDate')
    if publication_day and event_day and date.fromisoformat(event_day) < date.fromisoformat(publication_day) and not re.search(r'\bfile photo\b', caption, re.I):
        caption = 'File photo. ' + caption
    attribution = credit['credit'].strip()
    if not re.match(r'photo\b', attribution, re.I):
        attribution = 'Photo: ' + attribution
    combined = caption + ' ' + attribution
    if len(combined) > 2000:
        raise ValueError('Full photo caption and credit exceed the website limit of 2000 characters')
    return combined
